### ISSUE TITLE
this not found in RequestInformation

### ISSUE THREAD

**Issue by olafura** [microsoft/kiota-abstractions-ruby#32]
https://github.com/microsoft/kiota-abstractions-ruby/blob/f300eed9fad8ba0ecc94611e7c251775b179b958/lib/microsoft_kiota_abstractions/request_information.rb#L103

This should be `@content = writer.get_serialized_content();`

**Comment by baywet** [comment]
Hi @olafura 
Thanks for using kiota and for letting us know about this overlook.
Is this something you'd be willing to submit a pull request for?

**Comment by olafura** [comment]
@baywet done

Would you happen to also contribute to `microsoft_kiota_serialization_json`, and `microsoft_graph` because I need to commit small fixes for those also
